version: '3.5'

services:
  frontti:
    image: frontti
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
     - 3000:3000
  backi:
    image: backi
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports:
     - 5000:5000
    volumes:
     - model:/src/model
  training:
    image: training
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
     - images:/src/imgs
     - data:/src/data
     - model:/src/model
volumes:
  model:
  images:
  data:
